name: Github Actions Secret

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "RAPID_API_KEY:  "
          echo ${{ secrets.RAPID_API_KEY }}
        env:
          API_KEY: ${{secrets.API_KEY}}

        
